---
- name: Deploy Application
  hosts: all
  become: yes
  tasks:
    - name: Stop existing containers (if any)
      community.docker.docker_compose:
        project_src: /path/to/your/app/directory # Change this to your actual app directory on the server
        state: absent

    - name: Copy application files
      copy:
        src: /path/to/local/queue-me-project # Change this to your local project path
        dest: /path/to/remote/app/directory # Change this to your desired remote app directory
        remote_src: no

    - name: Build and start Docker containers
      community.docker.docker_compose:
        project_src: /path/to/remote/app/directory # Change this to your desired remote app directory
        state: present


