---
- name: Install Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present

    - name: Install git
      apt:
        name: git
        state: present


