# Dockerfile.server

# Use a Node.js base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY queue-me/server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY queue-me/server/ ./

# Expose the port the app runs on
EXPOSE 3002

# Start the app
CMD ["npm", "start"]
