# Dockerfile.server

# Use a Node.js image as the base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY queue-me-project/queue-me/server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY queue-me-project/queue-me/server/ ./

# Expose the port the Node.js app runs on
EXPOSE 3002

# Command to run the application
CMD ["npm", "start"]

